title: My Matter Value
lang: en
description: Website for my learning & gaining
author: Xiang Zhong

theme: null

edit: true
addons_branch: false


addons:
  - github:
    - homepage
    - download
  - i18n: false
  - plugins: false
  - analytics: none

# addons.analytics:
#     on  : it's on
#     off : it's off
#     none: viewer off but background running



copyright:
  revision: false

readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - jekyll-rtd-theme.gemspec
  - bash_updateThemeFromSource.sh
  - bash_updateChkDiff.sh
  - bash_searchKeyWord.sh
  - bash_findKeyWord.sh
  - info_mdRule.txt
  - jekyll-markdown.html
  - jekyll-markdown.md
  - ruby-liquid-debug.rb
  - Jekyll-rtd-theme.mm
  - Jekyll-variables.txt



nav_version: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-mermaid
mermaid:
  custom: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  initialize:
    startOnLoad: true
    logLevel: fatal
    flowchart:
      diagramPadding: 8
      htmlLabels: true
      curve: linear
    gantt:
      titleTopMargin: 25


