title: My Matter Value
lang: en
description: Website for my learning & gaining
author: Xiang Zhong

theme: null

edit: true
addons_branch: false


addons:
  - github:
    - homepage
    - download
  - i18n: false
  - plugins: false
  - analytics

copyright:
  revision: false

readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - jekyll-rtd-theme.gemspec
  - bash_updateThemeFromSource.sh
  - bash_updateChkDiff.sh



nav_version: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions



